// GENERATED by scripts/embed-fonts.mjs -- do not edit.

/** Fonts available for measurement, keyed by their /public path. */
export const EMBEDDED_FONTS = {
  '/fonts/LiberationMono-Regular.ttf': {
    slug: 'LiberationMono-Regular',
    byteLength: 319624,
    load: () => import('./LiberationMono-Regular'),
  },
  '/fonts/LiberationSans-Regular.ttf': {
    slug: 'LiberationSans-Regular',
    byteLength: 410820,
    load: () => import('./LiberationSans-Regular'),
  },
  '/fonts/LiberationSerif-Regular.ttf': {
    slug: 'LiberationSerif-Regular',
    byteLength: 393692,
    load: () => import('./LiberationSerif-Regular'),
  },
} as const;

export type EmbeddedFontPath = keyof typeof EMBEDDED_FONTS;
