// Embeds the two fillable PDFs the site serves, scrubbed, as base64 modules.
//
// The originals sit in forms-src/, which is not committed: they carry the
// maintainer's name and unit in their document information, and the
// promotion builder carries sample entries. This runs src/lib/pdfform/prepare
// over each -- through esbuild, since the preparation code is TypeScript and
// shared with the browser -- and writes what the site embeds under
// src/lib/pdfform/embedded/. Those generated files are committed; the
// originals never are. Run after replacing either source file:
//
//   node scripts/embed-forms.mjs
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const sourceDir = join(root, 'forms-src');
const outDir = join(root, 'src', 'lib', 'pdfform', 'embedded');

const FORMS = [
  { source: 'USAF_PFRA_Scoring.pdf', out: 'pt-calculator.ts', prepare: 'preparePt', label: 'PT calculator' },
  { source: 'promotion-script-builder.pdf', out: 'promotion-script.ts', prepare: 'preparePromotion', label: 'promotion script builder' },
];

const bundle = await build({
  entryPoints: [join(root, 'src', 'lib', 'pdfform', 'prepare-entry.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
  logLevel: 'silent',
});
const code = bundle.outputFiles[0].text;
const mod = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);

mkdirSync(outDir, { recursive: true });
for (const form of FORMS) {
  const path = join(sourceDir, form.source);
  if (!existsSync(path)) {
    console.log(`skip ${form.label}: ${path} not present`);
    continue;
  }
  const input = new Uint8Array(readFileSync(path));
  const output = await mod[form.prepare](input);
  const base64 = Buffer.from(output).toString('base64');
  const lines = base64.match(/.{1,120}/g) ?? [];
  const text =
    `// GENERATED by scripts/embed-forms.mjs -- do not edit.\n` +
    `// The ${form.label}, prepared for the site: document information scrubbed, unit text and\n` +
    `// sample entries removed, script matched to the site's. The source file is not committed.\n` +
    `export const byteLength = ${output.length};\n` +
    `export const base64 =\n  '${lines.join("' +\n  '")}';\n`;
  writeFileSync(join(outDir, form.out), text);
  console.log(`wrote ${form.out}: ${input.length} -> ${output.length} bytes`);
}
