#!/usr/bin/env node
/**
 * Generates src/lib/metrics/embedded/*.ts from the TTFs in public/fonts.
 *
 * Why embed rather than fetch: constraint 3 says a page saved to disk and opened
 * with no network must fully work. Under file:// a browser refuses fetch() and
 * XHR for local files (opaque origin), so `fetch('/fonts/x.ttf')` fails exactly
 * in the scenario the constraint exists to protect. Inlining the bytes is the
 * only way the measurement core survives that.
 *
 * The generated modules are committed so the build needs no extra step, and a
 * test asserts they still match the bytes in public/fonts.
 *
 * Run: npm run embed:fonts
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = join(root, 'public', 'fonts');
const outDir = join(root, 'src', 'lib', 'metrics', 'embedded');

mkdirSync(outDir, { recursive: true });

const files = readdirSync(fontsDir).filter((f) => f.toLowerCase().endsWith('.ttf')).sort();
if (files.length === 0) {
  console.error('No .ttf files in public/fonts');
  process.exit(1);
}

const index = [];

for (const file of files) {
  const bytes = readFileSync(join(fontsDir, file));
  const slug = basename(file, '.ttf');
  const base64 = bytes.toString('base64');
  const out = join(outDir, `${slug}.ts`);
  writeFileSync(
    out,
    `// GENERATED by scripts/embed-fonts.mjs -- do not edit.\n` +
      `// Source: public/fonts/${file} (${bytes.length} bytes)\n` +
      `// Liberation fonts are SIL Open Font License 1.1; see public/fonts/LICENSE-Liberation.txt\n` +
      `export const byteLength = ${bytes.length};\n` +
      `export const base64 =\n  '${base64}';\n`,
    'utf8',
  );
  index.push({ slug, file, bytes: bytes.length });
  console.log(`embedded ${file} -> ${slug}.ts (${(base64.length / 1024).toFixed(0)} KB base64)`);
}

writeFileSync(
  join(outDir, 'index.ts'),
  `// GENERATED by scripts/embed-fonts.mjs -- do not edit.\n\n` +
    `/** Fonts available for measurement, keyed by their /public path. */\n` +
    `export const EMBEDDED_FONTS = {\n` +
    index
      .map(
        (e) =>
          `  '/fonts/${e.file}': {\n` +
          `    slug: '${e.slug}',\n` +
          `    byteLength: ${e.bytes},\n` +
          `    load: () => import('./${e.slug}'),\n` +
          `  },`,
      )
      .join('\n') +
    `\n} as const;\n\n` +
    `export type EmbeddedFontPath = keyof typeof EMBEDDED_FONTS;\n`,
  'utf8',
);
console.log(`wrote index.ts with ${index.length} font(s)`);
