/**
 * Installation directories, generated.
 *
 * GENERATED by scripts/import-installations.mjs -- do not edit by hand.
 * Static imports on purpose: the offline single-file build runs through
 * esbuild, which cannot see a Vite glob.
 */
import type { DataFileRef } from '../../../lib/data/installationIndex';

import i0 from './kadena-ab.json';

export const INSTALLATION_FILES: DataFileRef[] = [
  ['src/data/firstsergeant/installations/kadena-ab.json', i0],
];
