import { loadDataset, isPlaceholderString } from './loader';
import {
  DataFileError,
  type AgencyCategory,
  type Contact,
  type Dataset,
  type Installation,
  type ReferenceEntry,
  type Situation,
  type Urgency,
} from './types';

import categoriesFile from '../../data/firstsergeant/categories.json';
import situationsFile from '../../data/firstsergeant/situations.json';
import referencesFile from '../../data/firstsergeant/references.json';
import nationalFile from '../../data/firstsergeant/national.json';
import exampleInstallation from '../../data/firstsergeant/installations/example.json';
import { INSTALLATION_FILES } from '../../data/firstsergeant/installations/index';

/**
 * First Sergeant Toolkit data.
 *
 * Four files, one job each: `categories` is the spine (every agency the toolkit
 * knows about), `situations` routes a presenting problem to a category,
 * `references` points at official publications, and each installation file
 * carries local contact details.
 *
 * `national` is the exception that makes the whole thing usable: Military
 * OneSource is the same number everywhere, answers around the clock, and can
 * route to the right local agency itself. So the toolkit always has a real
 * answer even with no installation populated, and it never has to invent one.
 *
 * Adding an installation is a data edit plus one line in RAW_INSTALLATIONS. If
 * it ever needs a component change, the abstraction has broken -- constraint 4.
 */

const CATEGORIES_FILE = 'src/data/firstsergeant/categories.json';
const SITUATIONS_FILE = 'src/data/firstsergeant/situations.json';
const REFERENCES_FILE = 'src/data/firstsergeant/references.json';
const NATIONAL_FILE = 'src/data/firstsergeant/national.json';

/**
 * Imported directories first, the template last.
 *
 * INSTALLATION_FILES is generated by scripts/import-installations.mjs from the
 * files actually on disk, so adding a base is running the importer -- no code
 * edit, per constraint 4.
 */
const RAW_INSTALLATIONS: ReadonlyArray<readonly [string, unknown]> = [
  ...INSTALLATION_FILES,
  ['src/data/firstsergeant/installations/example.json', exampleInstallation],
];

// ---------------------------------------------------------------------------
// Field readers
// ---------------------------------------------------------------------------

function obj(file: string, raw: unknown, what: string): Record<string, unknown> {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new DataFileError(file, `${what} must be an object`);
  }
  return raw as Record<string, unknown>;
}

function str(file: string, o: Record<string, unknown>, key: string, what: string): string {
  const value = o[key];
  if (typeof value !== 'string' || value === '') {
    throw new DataFileError(file, `${what} ${key} must be a non-empty string`);
  }
  return value;
}

/** A field a stub is allowed to leave blank. Never undefined, so the UI can just test for ''. */
function optional(o: Record<string, unknown>, key: string): string {
  const value = o[key];
  return typeof value === 'string' ? value.trim() : '';
}

function stringArray(file: string, raw: unknown, what: string): string[] {
  if (raw === undefined || raw === null) return [];
  if (!Array.isArray(raw)) throw new DataFileError(file, `${what} must be an array`);
  return raw.map((v, i) => {
    if (typeof v !== 'string' || v === '') {
      throw new DataFileError(file, `${what}[${i}] must be a non-empty string`);
    }
    return v;
  });
}

function list(file: string, o: Record<string, unknown>, key: string): unknown[] {
  const value = o[key];
  if (!Array.isArray(value) || value.length === 0) {
    throw new DataFileError(file, `data.${key} must be a non-empty array`);
  }
  return value;
}

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

function normalizeCategories(raw: unknown, _meta: unknown, file: string): AgencyCategory[] {
  const data = obj(file, raw, 'data');
  const seen = new Set<string>();
  return list(file, data, 'categories').map((entry, i) => {
    const o = obj(file, entry, `categories[${i}]`);
    const id = str(file, o, 'id', `categories[${i}]`);
    if (seen.has(id)) throw new DataFileError(file, `duplicate category id "${id}"`);
    seen.add(id);
    const urgency = o.urgency;
    if (urgency !== 'crisis' && urgency !== 'standard') {
      throw new DataFileError(file, `categories[${i}].urgency must be crisis or standard`);
    }
    return {
      id,
      label: str(file, o, 'label', `categories[${i}]`),
      blurb: str(file, o, 'blurb', `categories[${i}]`),
      urgency: urgency as Urgency,
      mosPages: stringArray(file, o.mosPages, `categories[${i}].mosPages`),
    };
  });
}

export const CATEGORIES: Dataset<AgencyCategory[]> = loadDataset(
  CATEGORIES_FILE,
  categoriesFile,
  normalizeCategories,
);

const CATEGORY_IDS = new Set(CATEGORIES.data.map((c) => c.id));

export function getCategory(id: string): AgencyCategory | undefined {
  return CATEGORIES.data.find((c) => c.id === id);
}

/** Crisis agencies first, then the rest, each keeping its declared order. */
export function categoriesByUrgency(): AgencyCategory[] {
  return [
    ...CATEGORIES.data.filter((c) => c.urgency === 'crisis'),
    ...CATEGORIES.data.filter((c) => c.urgency === 'standard'),
  ];
}

// ---------------------------------------------------------------------------
// References
// ---------------------------------------------------------------------------

function normalizeReferences(raw: unknown, _meta: unknown, file: string): ReferenceEntry[] {
  const data = obj(file, raw, 'data');
  const seen = new Set<string>();
  return list(file, data, 'references').map((entry, i) => {
    const o = obj(file, entry, `references[${i}]`);
    const id = str(file, o, 'id', `references[${i}]`);
    if (seen.has(id)) throw new DataFileError(file, `duplicate reference id "${id}"`);
    seen.add(id);
    return {
      id,
      topic: str(file, o, 'topic', `references[${i}]`),
      publication: optional(o, 'publication'),
      section: optional(o, 'section'),
      url: optional(o, 'url'),
    };
  });
}

export const REFERENCES: Dataset<ReferenceEntry[]> = loadDataset(
  REFERENCES_FILE,
  referencesFile,
  normalizeReferences,
);

const REFERENCE_IDS = new Set(REFERENCES.data.map((r) => r.id));

/** True once the entry actually points somewhere. */
export function isReferencePopulated(entry: ReferenceEntry): boolean {
  return !isPlaceholderString(entry.publication);
}

// ---------------------------------------------------------------------------
// Situations
// ---------------------------------------------------------------------------

function normalizeSituations(raw: unknown, _meta: unknown, file: string): Situation[] {
  const data = obj(file, raw, 'data');
  const seen = new Set<string>();
  return list(file, data, 'situations').map((entry, i) => {
    const what = `situations[${i}]`;
    const o = obj(file, entry, what);
    const id = str(file, o, 'id', what);
    if (seen.has(id)) throw new DataFileError(file, `duplicate situation id "${id}"`);
    seen.add(id);

    const startHere = str(file, o, 'startHere', what);
    if (!CATEGORY_IDS.has(startHere)) {
      throw new DataFileError(file, `${what} startHere names unknown category "${startHere}"`);
    }
    const alsoSee = stringArray(file, o.alsoSee, `${what}.alsoSee`);
    for (const cid of alsoSee) {
      if (!CATEGORY_IDS.has(cid)) {
        throw new DataFileError(file, `${what} alsoSee names unknown category "${cid}"`);
      }
      if (cid === startHere) {
        throw new DataFileError(file, `${what} lists "${cid}" as both startHere and alsoSee`);
      }
    }
    const referenceIds = stringArray(file, o.referenceIds, `${what}.referenceIds`);
    for (const rid of referenceIds) {
      if (!REFERENCE_IDS.has(rid)) {
        throw new DataFileError(file, `${what} names unknown reference "${rid}"`);
      }
    }
    return {
      id,
      label: str(file, o, 'label', what),
      startHere,
      alsoSee,
      questions: stringArray(file, o.questions, `${what}.questions`),
      referenceIds,
      keywords: stringArray(file, o.keywords, `${what}.keywords`),
    };
  });
}

export const SITUATIONS: Dataset<Situation[]> = loadDataset(
  SITUATIONS_FILE,
  situationsFile,
  normalizeSituations,
);

export function getSituation(id: string): Situation | undefined {
  return SITUATIONS.data.find((s) => s.id === id);
}

// ---------------------------------------------------------------------------
// Contacts: national and per-installation
// ---------------------------------------------------------------------------

function normalizeContact(file: string, raw: unknown, what: string): Contact {
  const o = obj(file, raw, what);
  const categoryId = str(file, o, 'categoryId', what);
  if (!CATEGORY_IDS.has(categoryId)) {
    throw new DataFileError(file, `${what} names unknown category "${categoryId}"`);
  }
  return {
    categoryId,
    name: optional(o, 'name'),
    phone: optional(o, 'phone'),
    dsn: optional(o, 'dsn'),
    location: optional(o, 'location'),
    hours: optional(o, 'hours'),
    url: optional(o, 'url'),
    notes: optional(o, 'notes'),
  };
}

/** A contact is usable when there is something to actually dial or open. */
export function isContactPopulated(contact: Contact): boolean {
  return (
    !isPlaceholderString(contact.phone) ||
    !isPlaceholderString(contact.dsn) ||
    !isPlaceholderString(contact.url)
  );
}

function normalizeNational(raw: unknown, _meta: unknown, file: string): Contact[] {
  const data = obj(file, raw, 'data');
  return list(file, data, 'resources').map((entry, i) =>
    normalizeContact(file, entry, `resources[${i}]`),
  );
}

export const NATIONAL: Dataset<Contact[]> = loadDataset(
  NATIONAL_FILE,
  nationalFile,
  normalizeNational,
);

function normalizeInstallation(raw: unknown, _meta: unknown, file: string): Installation {
  const data = obj(file, raw, 'data');
  const seen = new Set<string>();
  const contacts = list(file, data, 'contacts').map((entry, i) => {
    const contact = normalizeContact(file, entry, `contacts[${i}]`);
    if (seen.has(contact.categoryId)) {
      throw new DataFileError(file, `two contacts for category "${contact.categoryId}"`);
    }
    seen.add(contact.categoryId);
    return contact;
  });
  return {
    id: str(file, data, 'id', 'data'),
    label: str(file, data, 'label', 'data'),
    example: data.example === true,
    contacts,
  };
}

export const INSTALLATIONS: ReadonlyArray<Dataset<Installation>> = RAW_INSTALLATIONS.map(
  ([file, raw]) => loadDataset(file, raw, normalizeInstallation),
);

export function getInstallation(id: string): Dataset<Installation> | undefined {
  return INSTALLATIONS.find((i) => i.data.id === id);
}

/** Installations a Shirt could actually use. Excludes the shipped template. */
export function realInstallations(): ReadonlyArray<Dataset<Installation>> {
  return INSTALLATIONS.filter((i) => !i.data.example);
}

/**
 * The contact for one agency at one installation, falling back to the national
 * resource for that agency.
 *
 * The fallback is the point: an unpopulated base does not leave a Shirt with
 * nothing, it leaves them with Military OneSource, which can route locally.
 */
export function contactFor(
  installation: Installation | null,
  categoryId: string,
): { contact: Contact; scope: 'local' | 'national' } | null {
  const local = installation?.contacts.find((c) => c.categoryId === categoryId);
  if (local && isContactPopulated(local)) return { contact: local, scope: 'local' };
  const national = NATIONAL.data.find((c) => c.categoryId === categoryId);
  if (national && isContactPopulated(national)) return { contact: national, scope: 'national' };
  return null;
}

/** The always-available resources, for the empty state and the quick panel. */
export function nationalFallbacks(): Contact[] {
  return NATIONAL.data.filter(isContactPopulated);
}
